### ISSUE TITLE
UnhandledPromiseRejection Error on Saving file

### ISSUE THREAD

**Issue by tanmaykk9** [djizco/mern-boilerplate#8]
Whenever any new file is saved with changes, getting the error as UnhandledPromiseRejection. How can i resolve this error ?

**Comment by djizco** [comment]
Is there any more information in the error message? You may have some old code with an unhandled Promise somewhere, and it just shows the error every time. Does it show a file name in the error?

**Comment by tanmaykk9** [comment]
> Is there any more information in the error message? You may have some old code with an unhandled Promise somewhere, and it just shows the error every time. Does it show a file name in the error?

The error is not present when i installed nodemon v 2.0.7. Can you also please post a boilerplate in PERN Stack! It will be really very helpful.

**Comment by djizco** [comment]
> The error is not present when i installed nodemon v 2.0.7. 

Interesting, well seems like it's resolved by updating packages. Can you confirm that you are no longer having this issue so I can close it?

> Can you also please post a boilerplate in PERN Stack! It will be really very helpful.

A PERN stack is on my todo list! Hopefully, I can get around to it soon.

**Comment by tanmaykk9** [comment]
> > The error is not present when i installed nodemon v 2.0.7.
> 
> Interesting, well seems like it's resolved by updating packages. Can you confirm that you are no longer having this issue so I can close it?
> 
> > Can you also please post a boilerplate in PERN Stack! It will be really very helpful.
> 
> A PERN stack is on my todo list! Hopefully, I can get around to it soon.

Yes i am no longer having any issues after upgrading nodemon. Waiting for the PERN Stack soon! I have migrated the current setup to Postgresql. But having some trouble while setting session in node. Because currently, the session is setup using Mongoose.. If you could just post a code snippet for it in your git. It will be helpful.

**Comment by djizco** [comment]
I haven't used Postgres in a while, but if I come up with something I will be sure to post it. Good luck.
