### ISSUE TITLE
Dependency conflict: mongoose 

### ISSUE THREAD

**Issue by jmprns** [djizco/mern-boilerplate#9]
OS: Xubuntu 21.04
npm: v7.22
node: v16.9.0

![mern-error](https://i.ibb.co/jzvGrRx/mern-error.png)

**Comment by djizco** [comment]
Yeah I'm actually aware that this package throws an error when installing, however I verified that it does still work correctly. I'm working on a different solution, but for now left it in since it still works.

**Comment by mashaigra** [comment]
Hi
I removed this package from the package.json file and installed it manually using:
      npm install mongoose-auto-increment-reworked **--force**
Now, it's working

**Comment by djizco** [comment]
Removed mongoose-auto-increment-reworked as it is now out of date. Replaced with @typegoose/auto-increment. This can be safely removed from new projects anyway as it is only used if you need an auto-incrementing field like I'm doing with the 'user' field that starts with 1.
